Sprint 07
grishan999/MovieQuiz pull request #4
Opened 2024-12-03 00:27 UTC by grishan999

2024-12-03 14:40 UTC, Kirchberg requested changes
⚠️ Критические замечания (это нужно исправить обязательно):

1. Не смог проверить тесты `ArrayTests`, так как они не запустились, из-за того, что не находятся внутри одного из `XCTestCase` классов, необходимо поправить в соответствии с пунктом задания 3

Без исправлений этих пунктов, я не смогу принять у тебя работу. Если возникнут вопросы, обязательно задавай их Наставнику!

2024-12-03 14:40 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    //MARK: - Private vars
Было бы хорошо переименовать в `MARK: - Private Properties`. Также после и до MARK оставляют одну пустую строку кода, так легче отследить его и найти нужные секции кода, иначе он смешивается

2024-12-03 14:40 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    //MARK: - Private vars
Если интересно, то можно сделать расположение файла в таком духе по модификаторам доступа и названием `MARK`-ов
```swift
// MARK: - Public Types
// MARK: - Public Properties
// MARK: - Public Init
// MARK: - Public Methods

// MARK: - Internal Types
// MARK: - Internal Properties
// MARK: - Internal Init
// MARK: - Internal Methods
...
// MARK: - Private Types
// MARK: - Private Properties
// MARK: - Private Init
// MARK: - Private Methods
```

2024-12-03 14:40 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        presenter = MovieQuizPresenter(viewController: self)
Создание statisticService и alertPresenter можно вынести в метод `init`, тогда нам не придется использовать опиционал.
```swift
final class MovieQuizViewController: UIViewController, MovieQuizViewControllerProtocol {

    init() {
        self.alertPresenter = AlertPresenter()
        self.statisticService = StatisticService()

        super.init(nibName: nil, bundle: nil)
    }

    @available(*, unavailable)
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

}
```

А вот presenter можно создавать таким образом и не придется использовать !:
```swift
private lazy var presenter: MovieQuizPresenter = {
    let presenter = MovieQuizPresenter(viewController: self)
    return presenter
}()
```

2024-12-03 14:40 UTC, Kirchberg commented on MovieQuizPresenterTests/MovieQuizPresenterTests.swift
> +    }
Чтобы такой Mock меньше занимал места, методы можно писать таким образом:
```swift
func show(quizStep step: QuizStepViewModel) {}
func showQuizResult(_ result: QuizResultsViewModel) {}
...
```

2024-12-03 14:40 UTC, Kirchberg commented on MovieQuizUITests/MovieQuizUITests.swift
> +        sleep (3)
Лучше пробел не ставить внутри выражения, то есть лучше: 
```swift
sleep(3)
```

2024-12-03 14:40 UTC, Kirchberg commented on MovieQuizUnitTest/ArrayTests.swift
> +}
⚠️ Не смог проверить тесты, так как они не запустились, из-за того, что не находятся внутри одного из XCTestCase классов

2024-12-04 09:46 UTC, grishan999 commented on MovieQuizUnitTest/ArrayTests.swift
> +}
Кирилл, приветствую!
Внес правки в коммит 10 "[Bugs fixed after review]"

Отправил заявку на практикуме

2024-12-05 07:45 UTC, Kirchberg approved these changes
Не забудь вмерджить пул-реквест в основную ветку.
🎉 Поздравляю! Этот модуль завершен, впереди тебя ждет еще больше интересного о разработке под iOS!

2024-12-05 14:55 UTC, merged